version: "3.9"

services:
  mysql_server:
    image: docker.io/bitnami/mysql:5.7
    restart: unless-stopped
    container_name: appdb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST='%'
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
#    expose:
#      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:18
    container_name: node_app
    restart: on-failure
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
    ports:
      - "8080:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - mysql_server
    command: node index.js
#  traefik:
#    image: "traefik:v2.9"
#    container_name: "traefik"
#    command:
#      - "--log.level=DEBUG"
#      - "--api.insecure=true"
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.web.address=:80"
#    ports:
#      - "80:3000"
#      - "8080:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  db:
