version: "3.8"

services:
  mysql_server:
    image: docker.io/bitnami/mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_HOST="${MYSQL_HOST}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASS="${MYSQL_PASS}"
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    build: .
    command: npm start
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server
    stdin_open: true
    tty: true

volumes:
  db:
